services:
  - type: web
    name: whitewhale_ai_backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
      - key: GOOGLE_API_KEY
        sync: false  # This will need to be set manually in Render dashboard
    healthCheckPath: /health
